/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Sidebar1: [{type: 'autogenerated', dirName: '现代文学'}],
  Sidebar2: [{type: 'autogenerated', dirName: '当代文学'}],

};

export default sidebars;
