import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  Sidebar1: [{type: 'autogenerated', dirName: '现代文学'}],
  Sidebar2: [{type: 'autogenerated', dirName: '当代文学'}],
  Sidebar3: [{type: 'autogenerated', dirName: '现代汉语'}],
  Sidebar4: [{type: 'autogenerated', dirName: '公文写作'}],
  Sidebar5: [{type: 'autogenerated', dirName: '古代文学'}],
  Sidebar6: [{type: 'autogenerated', dirName: '交流区'}],
};

export default sidebars;
