name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - master # 当 push 到 master 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 使用Node.js缓存
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # Build Docusaurus
      - name: Build Docusaurus website
        run: npm run build
      
      # 使用 GitHub Pages 部署
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages # 使用 gh-pages 分支作为 GitHub Pages 的源分支